"""Add split_type to Bill

Revision ID: 7eb4bf5fedda
Revises: e26e37b28683
Create Date: 2026-02-03 07:40:35.255940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7eb4bf5fedda'
down_revision: Union[str, Sequence[str], None] = 'e26e37b28683'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bills', sa.Column('split_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False, server_default='manual'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bills', 'split_type')
    # ### end Alembic commands ###
