"""

Revision ID: cb0d734b954b
Revises: cf94ad8865fb
Create Date: 2026-02-04 10:57:45.251103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb0d734b954b'
down_revision: Union[str, Sequence[str], None] = 'cf94ad8865fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_sum', sa.BigInteger(), server_default='0', nullable=False))
        batch_op.alter_column('price',
               existing_type=sa.BIGINT(),
               server_default='0',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill_items', schema=None) as batch_op:
        batch_op.drop_column('item_sum')

    # ### end Alembic commands ###
