"""Add count to items and unique index to bill_user

Revision ID: e26e37b28683
Revises: 
Create Date: 2026-02-02 10:41:21.906797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e26e37b28683'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bill_items', sa.Column('count', sa.Integer(), nullable=False, server_default='1'))
    op.drop_index(op.f('ix_bills_users_bill_id'), table_name='bills_users')
    op.create_index('ix_bill_user_unique', 'bills_users', ['bill_id', 'user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bill_user_unique', table_name='bills_users')
    op.create_index(op.f('ix_bills_users_bill_id'), 'bills_users', ['bill_id'], unique=False)
    op.drop_column('bill_items', 'count')
    # ### end Alembic commands ###
